### ISSUE TITLE
add_user.html is missing

### ISSUE THREAD

**Issue by ikus060** [elwlwlwk/ansible-web#1]
Hello looking forward to test your interface for Ansible. Look like one template is missing: add_user.html

**Comment by elwlwlwk** [comment]
Thanks to report. I leaved the company that I made this app so I don't have missing files. But I reimplemented depend on my memory.

**Comment by elwlwlwk** [comment]
i find you and i ki

**Comment by elwlwlwk** [comment]
i find you and i ki
